services:
  app:
    build:
      context: .
      args:
        - TF_VERSION=${TF_VERSION:-latest}
        - ARCH=${ARCH:-x86_64}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ~/.aws/:/home/developer/.aws
      - ~/.ssh/:/home/developer/.ssh
      - ~/.gitconfig:/home/developer/.gitconfig
      - ${BASHRC_PATH:-./.bashrc}:/home/developer/.bashrc
      - ../:/home/developer/workspace
